[package]
name = "clients-rs"
version = "0.1.0"
authors = ["Sharaf Zaman <sharafzaz121@gmail.com>"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "json"] }
serde_json = "1.0"
log = "0.4"